spring.application.name=bookstore

#spring.datasource.url=jdbc:mysql://localhost:3306/bookstore?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore?allowPublicKeyRetrieval=true&useSSL=false


server.port=9090

spring.datasource.username=root

# write your password here
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql

spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:change-me-please-change-me-please-change-me-please}
jwt.issuer=bookstore
jwt.exp-minutes=120
cors.allowed-origins=http://localhost:5173,http://localhost:5174



logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
logging.level.org.springframework.web.servlet.handler=TRACE


logging.level.org.springframework.aop=TRACE
logging.level.org.springframework.aop.framework.autoproxy=TRACE


server.error.include-exception=true
server.error.include-stacktrace=ALWAYS
spring.mvc.log-request-details=true

paypal.client-id=ATqXEU_-wixDaZq64240QLOfyBWBzyYCa8RMEyF-KpBji7tTQsfjnvvPOXA1b3VItY6T3dUQg_RuEf5z
paypal.client-secret=EHblYba_oVz3GR_MqoCh30ZW_77GEOfR09hbkLdQD9VNurcxU14kwczAs0a5sm-Mmo_oM8Ne2Q1U8vfk
paypal.base-url=https://api.sandbox.paypal.com


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

debug=true